export type { DatabaseConnection } from "@/database/prisma-utils"
export { checkDatabaseHealth } from "@/database/prisma-utils"
export type { LoggerConfig } from "@/logger/logger-config"
export { createFastifyLogger, createLogger } from "@/logger/logger-config"
export { registerRequestLogging } from "@/middleware/request-logging"
export type { SwaggerConfig } from "@/plugins/swagger-plugin"
export { registerSwagger } from "@/plugins/swagger-plugin"
export type { ApiInfo } from "@/routes/api-routes"
export { registerApiRoutes } from "@/routes/api-routes"
export type { DatabaseHealthData, HealthData } from "@/routes/health-routes"
export { registerHealthRoutes } from "@/routes/health-routes"
export { registerSentryDebugRoute, registerSentryErrorHandler } from "@/sentry/fastify-sentry"
export type { SentryConfig } from "@/sentry/sentry-config"
export { initializeSentry, isSentryInitialized, Sentry } from "@/sentry/sentry-config"
export type { ServerConfig } from "@/server/create-server"
export { createServer } from "@/server/create-server"
export type { StartServerConfig } from "@/utils/start-server"
export { startServer } from "@/utils/start-server"
